receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317

exporters:
  clickhouse:
    endpoint: clickhouse://clickhouse:9000?dial_timeout=10s&compress=lz4
    username: default
    ttl: 72h
    database: otel
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s

processors:
  batch:
    timeout: 5s

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
